---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ryann1908.
--- DateTime: 22/04/2021 17:08
---

gallery_one_items = {}

table.insert(gallery_one_items, { 'Prologue', function()

    --

end  })

table.insert(gallery_one_items, { 'Endings', function()

    --

end  })

table.insert(gallery_one_items, { 'Omake', function()

    --

end  })

table.insert(gallery_one_items, { 'Staff Roll', function()

    --

end  })

table.insert(gallery_one_items, { 'Concept Art', function()

    menu.FlyIn2(menu_gallery_art, 'right')
    menu.FlyOut(menu_gallery, 'left')

end  })

table.insert(gallery_one_items, { 'exit', function()

    UaupTheGallery(menu_gallery)

end  })

------------------------------------------------------------------------

gallery_art_items = {}

table.insert(gallery_art_items, { 'Reimu Concept Art', function()

    --

end  })

table.insert(gallery_art_items, { 'Umibiyo Concept Art', function()

    --

end  })

table.insert(gallery_art_items, { 'Jun Concept Art', function()

    --

end  })

table.insert(gallery_art_items, { 'Unk Concept Art', function()

    --

end  })

table.insert(gallery_art_items, { 'Rachel Concept Art', function()

    --

end  })

table.insert(gallery_art_items, { 'Other Concept Art', function()

    --

end  })

table.insert(gallery_art_items, { 'exit', function()

    menu.FlyIn2(menu_gallery, 'left')
    menu.FlyOut(menu_gallery_art, 'right')

end  })

------------------------------------------------------------------------

function UaupTheGallery(self)
    task.New(self, function()
        for i=255, 0, -255/12 do
            self._a = i
            task.Wait(1)
        end
        stage_menu.save_replay = false
        stage.Set('none', 'menu')
    end)
end

function InitializeGallery()
    menu_gallery = New(simple_menu, 'Gallery', gallery_one_items)
    menu_gallery_art = New(simple_menu, 'Concept Art', gallery_art_items)
end
